### ISSUE TITLE
Does not calculate merge commits into contributions

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/traces#20]
The main ideas is to exclude the merge commits to the counter of contributions.

**Comment by PrestaEdit** [comment]
WDYT about this, @PierreRambaud | @eternoendless | @Progi1984 | @matks ?

**Comment by eternoendless** [comment]
I think commits skew the volume of contribution too much and we should only count PRs as we did before.

**Comment by matks** [comment]
I don't see a lot of value into ignoring merge commits.

If you are trying to improve how contributions are "sized" there's other issues way bigger.

As said by @eternoendless, using commits are unit of value is not relevant on PrestaShop, see example PR https://github.com/PrestaShop/PrestaShop/pull/27442 which contains 18 commits. Is it 9x times more valuable than PR https://github.com/PrestaShop/PrestaShop/pull/27236 than contains 2 commits?

**Comment by PrestaEdit** [comment]
Of course is not but is the Trace system really count the number of commit into a Pull Request or only two: the main one, and the merge commit ? 🤔 

About merge commit, it's not valuable as it gives sometimes contributions to the same author (not really inside the core but on another projets) and doesn't deserve the reviewers of a Pull Request for example.

Main goal is to make valuable all datas: issues, QA, reviews and pull request, not only commits.
But first step and/or first specs could be to decide to change that with a small step, maybe.
